
services:
  rust-bot:
    build:
      context: "../.."
      dockerfile: ./docker/addfromhost/Dockerfile
    container_name: rust-telegrambot
    ports:
      - 8080:8080
    environment:
      - "TELOXIDE_LOG_DIR=/var/log/telegrambot/"
      - "TELOXIDE_DATA_DIR=/var/lib/telegrambot/"
      - "DATABASE_URL=sqlite:///var/lib/telegrambot/sqlite.db"
      - "TELOXIDE_BIND_PORT=8080"
      - TELOXIDE_PUBLIC_URL
      - TELOXIDE_TOKEN
    volumes:
      - ./log/:/var/log/telegrambot/
      - ../../.env:/.env
      - ./data/:/var/lib/telegrambot/
    networks:
      telegramnet:
        # static ip for reverse proxy (e.g. nginx/traefik)
        ipv4_address: 192.168.16.200

networks:
  telegramnet:
    name: telegram_network
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/24
          ip_range: 192.168.16.0/24
