
services:
  rust-bot:
    build:
      context: "../.."
      dockerfile: ./docker/addfromhost/Dockerfile
    container_name: rust-telegrambot
    ports:
      - 8080:8080
    environment:
      # default configuration
      - "TELOXIDE_LOG_DIR=/var/log/telegrambot/"
      - "TELOXIDE_DATA_DIR=/var/lib/telegrambot/"
      - "DATABASE_URL=sqlite:///var/lib/telegrambot/sqlite.db"
      - "TELOXIDE_BIND_PORT=8080"
      # user provided configuration via .env
      - TELOXIDE_PUBLIC_URL
      - TELOXIDE_TOKEN
    volumes:
      - ./log/:/var/log/telegrambot/
      - ../../.env:/.env
      - ./data/:/var/lib/telegrambot/
    # in case you use traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.telegrambot.rule=Host(`bot.example.org`)
      - traefik.http.routers.telegrambot.tls=true
      - traefik.http.services.telegrambot.loadbalancer.server.port=8080

    # in case you use another reverse proxy, e.g. nginx
    networks:
      telegramnet:
        # static ip for reverse proxy (e.g. nginx)
        ipv4_address: 192.168.16.200

networks:
  telegramnet:
    name: telegram_network
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/24
          ip_range: 192.168.16.0/24
